clear scr;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PHONGBAN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEAN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PHANCONG CASCADE CONSTRAINTS';
END;
/

CREATE TABLE NHANVIEN (
    MANV CHAR(5),
    TENNV NVARCHAR2(150) NOT NULL,
    PHAI VARCHAR(10) DEFAULT 'private',
    NGAYSINH DATE NULL,
    DIACHI NVARCHAR2(200) NULL,
    SODT VARCHAR(10) NULL,
    LUONG FLOAT NULL,
    PHUCAP FLOAT NULL,
    VAITRO NVARCHAR2(50),
    MANQL CHAR(5) NULL,
    PHG CHAR(5),
    
    CONSTRAINT NHANVIEN_PK PRIMARY KEY(MANV),
    
    CONSTRAINT NHANVIEN_PHAI CHECK(
        PHAI IN ('private', 'male', 'female')
    ),
    CONSTRAINT NHANVIEN_LUONG CHECK(LUONG >= 0),
    CONSTRAINT NHANVIEN_PHUCAP CHECK(PHUCAP >= 0),
    CONSTRAINT NHANVIEN_VAITRO CHECK(
        VAITRO IN (
            'Nhân viên', 
            'QL tr?c ti?p',
            'Trý?ng ph?ng',
            'Tài chính',
            'Nhân s?',
            'Trý?ng ð? án',
            'Ban giám ð?c'
        )
    )
);

CREATE TABLE PHONGBAN(
    MAPB CHAR(5),
    TENPB NVARCHAR2(100) NOT NULL,
    TRPHG CHAR(5) NOT NULL,
    
    CONSTRAINT PHONGBAN_PK PRIMARY KEY(MAPB)
);

CREATE TABLE DEAN(
    MADA CHAR(5),
    TENDA NVARCHAR2(150) NOT NULL,
    NGAYBD DATE NOT NULL,
    PHONG CHAR(5),
    
    CONSTRAINT DEAN_PK PRIMARY KEY(MADA)
);

CREATE TABLE PHANCONG(
    MANV CHAR(5) NOT NULL,
    MADA CHAR(5) NOT NULL,
    THOIGIAN DATE NOT NULL,
    
    CONSTRAINT PHANCONG_PK PRIMARY KEY(MANV, MADA)
);

ALTER TABLE NHANVIEN 
    ADD CONSTRAINT NHANVIEN_NHANVIEN_MANGQL_MANV
    FOREIGN KEY(MANQL) 
    REFERENCES NHANVIEN(MANV);

ALTER TABLE NHANVIEN
    ADD CONSTRAINT NHANVIEN_PHONGBAN_PHG_MAPB
    FOREIGN KEY(PHG)
    REFERENCES PHONGBAN(MAPB);
    
ALTER TABLE PHONGBAN
    ADD CONSTRAINT PHONGBAN_NHANVIEN_TRPHG_MANV
    FOREIGN KEY(TRPHG)
    REFERENCES NHANVIEN(MANV);
    
ALTER TABLE DEAN
    ADD CONSTRAINT DEAN_PHONGBAN_PHONG_MAPB
    FOREIGN KEY(PHONG)
    REFERENCES PHONGBAN(MAPB);
    
ALTER TABLE PHANCONG
    ADD CONSTRAINT PHANCONG_NHANVIEN_MANV_MANV
    FOREIGN KEY(MANV)
    REFERENCES NHANVIEN(MANV);

ALTER TABLE PHANCONG
    ADD CONSTRAINT PHANCONG_DEAN_MADA_MADA
    FOREIGN KEY(MADA)
    REFERENCES DEAN(MADA);
    