CONN SYS/admin@//localhost:1521/ATBM_QLNV_PDB AS SYSDBA;
SHOW CON_NAME;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
ALTER SESSION SET CURRENT_SCHEMA = SYS;
DROP USER ATBM_QLNV CASCADE;

EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;

CREATE USER ATBM_QLNV IDENTIFIED BY team18;
GRANT UNLIMITED TABLESPACE TO ATBM_QLNV;
GRANT DBA TO ATBM_QLNV;
GRANT CONNECT, CREATE SESSION TO ATBM_QLNV;
GRANT EXECUTE ON DBMS_RLS TO ATBM_QLNV;
GRANT EXECUTE ANY PROCEDURE TO ATBM_QLNV;
GRANT ALL PRIVILEGES TO ATBM_QLNV WITH ADMIN OPTION;
GRANT CREATE ANY PROCEDURE TO ATBM_QLNV;
GRANT LBAC_DBA TO ATBM_QLNV;
GRANT EXECUTE ON SA_COMPONENTS TO ATBM_QLNV;
GRANT EXECUTE ON SA_LABEL_ADMIN TO ATBM_QLNV;
GRANT EXECUTE ON SA_USER_ADMIN TO ATBM_QLNV;
GRANT EXECUTE ON CHAR_TO_LABEL TO ATBM_QLNV;

ALTER USER LBACSYS IDENTIFIED BY LBACSYS ACCOUNT UNLOCK;
GRANT INHERIT PRIVILEGES ON USER SYS TO LBACSYS;

BEGIN
    EXECUTE IMMEDIATE 'DROP USER TGD CASCADE';
    EXECUTE IMMEDIATE 'DROP USER TP_SX_MN CASCADE';
    EXECUTE IMMEDIATE 'DROP USER TP_SX_MB CASCADE';
    EXECUTE IMMEDIATE 'DROP USER TP_GC_MN CASCADE';
    EXECUTE IMMEDIATE 'DROP USER GB_MB CASCADE';
EXCEPTION
    WHEN OTHERS THEN RETURN;
END;
/

SELECT STATUS FROM DBA_OLS_STATUS WHERE NAME = 'OLS_CONFIGURE_STATUS';
SELECT BANNER, BANNER_FULL FROM v$version;
SELECT VALUE FROM V$OPTION WHERE PARAMETER = 'Oracle Label Security';
SHOW PDBS;