CONNECT ATBM_QLNV/team18@//localhost:1521/ATBM_QLNV_PDB;
--ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
ALTER SESSION SET CURRENT_SCHEMA=ATBM_QLNV;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PHONGBAN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE DEAN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PHANCONG CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE THONGBAO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE KEY_STORAGE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN RETURN;
END;
/

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(5),
    TENNV NVARCHAR2(150) NOT NULL,
    PHAI VARCHAR(10) DEFAULT 'private',
    NGAYSINH DATE NULL,
    DIACHI NVARCHAR2(200) NULL,
    SODT VARCHAR(10) NULL,
    LUONG VARCHAR2(128) DEFAULT NULL,
    PHUCAP VARCHAR2(128) DEFAULT NULL,
    VAITRO NVARCHAR2(50),
    MANQL VARCHAR2(5) NULL,
    PHG CHAR(5) NULL,
    
    CONSTRAINT NHANVIEN_PK PRIMARY KEY(MANV),
    
    CONSTRAINT NHANVIEN_PHAI CHECK(
        PHAI IN ('private', 'male', 'female')
    ),
    CONSTRAINT NHANVIEN_VAITRO CHECK(
        VAITRO IN (
            'Nhan vien', 
            'QL truc tiep',
            'Truong phong',
            'Tai chinh',
            'Nhan su',
            'Truong de an',
            'Ban giam doc'
        )
    )
);

CREATE TABLE PHONGBAN(
    MAPB CHAR(5),
    TENPB NVARCHAR2(100) NOT NULL,
    TRPHG VARCHAR2(5) NULL,
    
    CONSTRAINT PHONGBAN_PK PRIMARY KEY(MAPB)
);

CREATE TABLE DEAN(
    MADA CHAR(5),
    TENDA NVARCHAR2(150) NOT NULL,
    NGAYBD DATE NOT NULL,
    PHONG CHAR(5) NULL,
    
    CONSTRAINT DEAN_PK PRIMARY KEY(MADA)
);

CREATE TABLE PHANCONG(
    MANV VARCHAR2(5) NOT NULL,
    MADA CHAR(5) NOT NULL,
    THOIGIAN DATE NOT NULL,
    
    CONSTRAINT PHANCONG_PK PRIMARY KEY(MANV, MADA)
);

ALTER TABLE NHANVIEN 
    ADD CONSTRAINT NHANVIEN_NHANVIEN_MANGQL_MANV
    FOREIGN KEY(MANQL) 
    REFERENCES NHANVIEN(MANV)
    ON DELETE SET NULL;

ALTER TABLE NHANVIEN
    ADD CONSTRAINT NHANVIEN_PHONGBAN_PHG_MAPB
    FOREIGN KEY(PHG)
    REFERENCES PHONGBAN(MAPB)
    ON DELETE SET NULL;

ALTER TABLE PHONGBAN
    ADD CONSTRAINT PHONGBAN_NHANVIEN_TRPHG_MANV
    FOREIGN KEY(TRPHG)
    REFERENCES NHANVIEN(MANV)
    ON DELETE SET NULL;
    
ALTER TABLE DEAN
    ADD CONSTRAINT DEAN_PHONGBAN_PHONG_MAPB
    FOREIGN KEY(PHONG)
    REFERENCES PHONGBAN(MAPB)
    ON DELETE SET NULL;
    
ALTER TABLE PHANCONG
    ADD CONSTRAINT PHANCONG_NHANVIEN_MANV_MANV
    FOREIGN KEY(MANV)
    REFERENCES NHANVIEN(MANV);

ALTER TABLE PHANCONG
    ADD CONSTRAINT PHANCONG_DEAN_MADA_MADA
    FOREIGN KEY(MADA)
    REFERENCES DEAN(MADA);

-- Trigger cap nhat VAITRO QL truc tiep khi duoc gan MANQL cho nhan vien khac
CREATE OR REPLACE TRIGGER TG_ASSIGN_DIRECT_MANAGER
BEFORE INSERT OR UPDATE OF MANQL ON NHANVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MANQL IS NOT NULL THEN
        UPDATE NHANVIEN
        SET VAITRO = 'QL truc tiep'
        WHERE MANV = :NEW.MANQL;
    END IF;
END;
/

-- Trigger cap nhat vai tro Truong phong khi duoc gan lam TRPHG cho phong ban cua chinh nhan vien do
CREATE OR REPLACE TRIGGER TG_ASSIGN_DEPARTMENT_MANAGER
AFTER UPDATE OF TRPHG ON PHONGBAN
FOR EACH ROW
DECLARE 
    VERIFIER NUMBER := 0;
    VERIFY_FAIL EXCEPTION;
    
BEGIN
    UPDATE NHANVIEN
    SET VAITRO = 'Nhan vien'
    WHERE VAITRO = 'Truong phong' and PHG = :NEW.MAPB;
    
    SELECT COUNT(*) INTO VERIFIER
    FROM NHANVIEN
    WHERE PHG = :NEW.MAPB AND MANV = :NEW.TRPHG;
    
    IF VERIFIER > 0 THEN
        UPDATE NHANVIEN
        SET VAITRO = 'Truong phong'
        WHERE PHG = :NEW.MAPB AND MANV = :NEW.TRPHG;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'CANNOT ASSIGN OTHER DEPARTMENT EMPLOYEE AS THE MANAGER OF DEPARTMENT');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TG_DELETE_DEPARTMENT
AFTER DELETE ON PHONGBAN
FOR EACH ROW
BEGIN   
    RETURN;
--    UPDATE NHANVIEN
--    SET VAITRO = 'Nhân viên'
--    WHERE PHG = :NEW.MAPB AND (VAITRO = 'Truong phong' OR MANV = :NEW.TRPHG);
END;
/

CREATE TABLE THONGBAO(
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NOIDUNG NVARCHAR2(2000)
);

