--SET WRAP OFF;
--ALTER SESSION SET CURRENT_SCHEMA=ATBM_QLNV;

-- OLS TESTCASES
CONNECT ATBM_QLNV/team18@//localhost:1521/ATBM_QLNV_PDB;
INSERT INTO ATBM_QLNV.THONGBAO(NOIDUNG, ROW_LABEL)
VALUES('TO TGD', CHAR_TO_LABEL('ATBM_QLNV_OLS_TEST26', 'L_BGD:C_MB,C_SX,C_GC:G_TQ'));
INSERT INTO ATBM_QLNV.THONGBAO(NOIDUNG, ROW_LABEL)
VALUES('TO GB_MB', CHAR_TO_LABEL('ATBM_QLNV_OLS_TEST26', 'L_BGD:C_MB,C_SX,C_GC:G_MB'));
INSERT INTO ATBM_QLNV.THONGBAO(NOIDUNG, ROW_LABEL)
VALUES('TO TP_SX_MN', CHAR_TO_LABEL('ATBM_QLNV_OLS_TEST26', 'L_TP:C_SX:G_MN'));
INSERT INTO ATBM_QLNV.THONGBAO(NOIDUNG, ROW_LABEL)
VALUES('TO TP_SX_MB', CHAR_TO_LABEL('ATBM_QLNV_OLS_TEST26', 'L_TP:C_SX:G_MB'));
INSERT INTO ATBM_QLNV.THONGBAO(NOIDUNG, ROW_LABEL)
VALUES('TO TP_GC_MN', CHAR_TO_LABEL('ATBM_QLNV_OLS_TEST26', 'L_TP:C_GC:G_MN'));

SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT TGD/TGD@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;
--DELETE FROM ATBM_QLNV.THONGBAO;

CONNECT TP_SX_MN/TP_SX_MN@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT TP_SX_MB/TP_SX_MB@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT TP_GC_MN/TP_GC_MN@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT GB_MB/GB_MB@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;

-- AUDIT TESTCASES
-- a)
CONNECT NV294/NV294@//localhost:1521/ATBM_QLNV_PDB;
UPDATE ATBM_QLNV.PHANCONG 
SET THOIGIAN = '21-MAR-21' 
WHERE MANV = '013';

CONNECT ATBM_QLNV/team18@//localhost:1521/ATBM_QLNV_PDB;
SELECT CURRENT_USER, OBJECT_NAME, POLICY_NAME, SQL_TEXT, TIMESTAMP
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'PHANCONG';

-- b)
CONNECT NV275/NV275@//localhost:1521/ATBM_QLNV_PDB;
SELECT MANV, LUONG, PHUCAP
FROM ATBM_QLNV.NHANVIEN
WHERE MANV = '202';

CONNECT ATBM_QLNV/team18@//localhost:1521/ATBM_QLNV_PDB;
SELECT CURRENT_USER, OBJECT_NAME, POLICY_NAME, SQL_TEXT, TIMESTAMP
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'NHANVIEN';

-- c)
CONNECT ATBM_QLNV/team18@//localhost:1521/ATBM_QLNV_PDB;
GRANT UPDATE ON ATBM_QLNV.NHANVIEN TO NV001;

CONNECT NV001/NV001@//localhost:1521/ATBM_QLNV_PDB;
SET SERVEROUTPUT ON FORMAT WRAPPED;
UPDATE ATBM_QLNV.NHANVIEN
SET LUONG = 100
WHERE MANV = '002';

CONNECT ATBM_QLNV/team18@//localhost:1521/ATBM_QLNV_PDB;
SELECT CURRENT_USER, OBJECT_NAME, POLICY_NAME, SQL_TEXT, TIMESTAMP
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'NHANVIEN' AND CURRENT_USER = 'NV001';
