--SET WRAP OFF;
--ALTER SESSION SET CURRENT_SCHEMA=ATBM_QLNV;
CONNECT ATBM_QLNV/team18@//localhost:1521/ATBM_QLNV_PDB;
DELETE FROM ATBM_QLNV.THONGBAO;
INSERT INTO ATBM_QLNV.THONGBAO(NOIDUNG, ROW_LABEL)
VALUES('TO TGD', CHAR_TO_LABEL('ATBM_QLNV_OLS_TEST26', 'L_BGD:C_MB,C_SX,C_GC:G_TQ'));
INSERT INTO ATBM_QLNV.THONGBAO(NOIDUNG, ROW_LABEL)
VALUES('TO GB_MB', CHAR_TO_LABEL('ATBM_QLNV_OLS_TEST26', 'L_BGD:C_MB,C_SX,C_GC:G_MB'));

SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT TGD/TGD@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT TP_SX_MN/TP_SX_MN@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT TP_SX_MB/TP_SX_MB@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT TP_GC_MN/TP_GC_MN@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;

CONNECT GB_MB/GB_MB@//localhost:1521/ATBM_QLNV_PDB;
SELECT * FROM ATBM_QLNV.THONGBAO;
CONNECT ATBM_QLNV/team18@//localhost:1521/ATBM_QLNV_PDB;
GRANT ROLE_NHANVIEN_ATBM TO NV001;
SELECT * FROM ATBM_QLNV.NHANVIEN;
CONNECT NV001/NV001@//localhost:1521/ATBM_QLNV_PDB;
SELECT VAITRO FROM ATBM_QLNV.NHANVIEN;
SELECT * FROM CDB_ROLE_PRIVS WHERE GRANTEE = 'NV001';
