ALTER SESSION SET CURRENT_SCHEMA=ATBM_QLNV;

--SELECT * FROM NHANVIEN;
DROP USER SCO CASCADE;
CREATE USER SCO IDENTIFIED BY SCO;
GRANT CONNECT TO SCO;   
--GRANT SELECT ANY TABLE TO SCO;
--GRANT SELECT ON NHANVIEN TO SCO;